
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import ClerkProviderWithConfig from "./clerk-provider";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import HideSidebarOnHome from "./HideSidebarOnHome";
import ClientUserMenuWrapper from "./ClientUserMenuWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interSans.variable} ${robotoMono.variable}`}>
      <body>
        <ClerkProviderWithConfig>
          <ClientUserMenuWrapper />
          <HideSidebarOnHome>{children}</HideSidebarOnHome>
        </ClerkProviderWithConfig>
      </body>
    </html>
  );
}
